name: Continuous Integration

on: [push]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        version: [1.87.0]
        variant: [debug, release]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ghcr.io/throttr/builder-alpine:${{ matrix.version }}-${{ matrix.variant }}
          build-args: |
            BOOST_VERSION=${{ matrix.version }}
            BOOST_VARIANT=${{ matrix.variant }}
